language: php
php:
- 7.1
before_script:
- cp .env.travis .env
- mysql -e 'create database homestead_test'
- composer self-update
- composer install --no-interaction
script:
- vendor/bin/phpunit
deploy:
  provider: heroku
  api_key:
    secure: VZGmfP0fFhLmShBWBFlJTZzxyuDOn+OtYl1Yr9XzLtN7d4qHT58kKIVynjuMtOxt8c3VnlDwzZ4bXEzIAd5qdjB+DZmMukQFxdKtv0DVklgc+16/TR/cZEn0V7b42uGJm9pzC5ws3UMeoHBXFAPKpXEjDngqNJy56drHph30Rmdx9y/i9zgJOnN4F2uTdo6eHyg/yj9PwHlZjHszF3VlzJHTjLOpJMVk6+F8dbew5GxecgMZo9kmBLOtyjgz7N1CSZwhEMm2pw+9V5tUy0QxiVUX5+ZAb5zd6PU9/sFZ9BMwEUmLeVlloNjvdlBwm1Di0b+VC90txBU0LYDNiDRt0IG9smJQEdDvs+6FesoHhQ8yt8nRTqaq1uTr0eHjfRM+Mtnoj83VT4wgw+kRdTK3+498+CxK4Mg1GsWKCIL4Ry0GU58VD2JB7LuAj/xpTDEpQ7Suo9lTPaSJxozo4fZfPz6w2mCJ1xkf9/wayVRUp6uminPDug2eb0VuulV7CWmw2fZxba7w3Vt6LTTYc7oaR9fjC7Eordf8IUTVdH3+Qb9+Lq7aC4z1RYG2TPwW3YMr9euDDwwS1fSdc2l2EdI5IHXhBO/NRDn8jbDG6zg6MB2gtf3AXu0C1IK/+mc23Kzmg8uljqWoTml8WoRsj+9s2vxBy7rAMbA+iQnbK170T4s=
