language: php
php:
- 7.1
before_script:
- cp .env.travis .env
- mysql -e 'create database homestead_test'
- composer self-update
- composer install --no-interaction
- heroku config:get DATABASE_URL -a jwtbackend
- php artisan migrate
script:
- vendor/bin/phpunit
deploy:
  provider: heroku
  api_key:
    secure: N3v47nmahCzAnv4+b33MriHhn4OCesIKgbc4qt8MxDzTVrQsFGNIQDX1rFoNQsRomUViMGLybmRO80fH967PXuwcX4V7tMZDwHONYHAC8Afii6rBypS7VsXne+4zD54hwWCws8Nt9VSg2WhfFww2zw1ZLW7RcRmtQBdN4Sg5Pn1K4hbnj0MtQzYRqStH3EBkOYwSCFi1LhwkBJG7HtGMsEk+Er6mE2ZAwAGONGo0KLoDPWpCVCuIaSTZv5+wLkSlGH4ptbTso/xylvm2mJJ9tCfFT4eWif7hUwjfvk0B97DezzihJUkpHEkWK2PkNP4wQu+Y/ydSp7UNfTeGvYjZwdzB7U2fB2TEnv73gtD1Kpesnn7woQ0pVMo/R7q+6Ncy8nxeFxzghOvg8R5dUamz9nZGHyzc7Fg6phWGDqBysG4mf1bctcG9+XwP9KigKB7yFlE355HwwHaIv8+Qr49/0CRtg755NOUNqENaMDHWA/WeVb1jEiUFuUd+WgzeXwykZHdZFO7dLSLe6/CeLVdge+qEQtqzXmuEi624eIvd+Z6bE0CVJUhHk2q7Jko1syWu549cu81cPUfeE67wkrrmwNj6kwBL+pZmKChrPkquxJIjcOJp/fVhzYp2RxlyjvUYf8qCiTJlrPLFAK0XaI8wsF3INAkYvqxA7hZtR98L4t8=
  app: jwtbackend
